apiVersion: v2
name: workshop-test
description: A Helm chart for Kubernetes
type: application
dependencies:
  - name: rhel-demo
    repository: oci://ghcr.io/afekc/helm
    version: "1.0.3"
    alias: deploy1
  - name: rhel-demo
    repository: oci://ghcr.io/afekc/helm
    version: "1.0.3"
    alias: deploy2
version: 1.0.0
appVersion: "1.0.0"